

**Manual Tasks:**
Review Data Quality Reports: Manually review data quality reports generated from the automated processes to identify any issues that require manual intervention.

Handle Exceptions: Manually handle exceptions or special cases that cannot be handled through automated processes.

Long-Term Improvements and Roadmap:
Continuous Monitoring: Implement a system for continuous monitoring of data quality, with alerts for anomalies or issues.In my compaany I used Azure data Factory ETL pipelines and monitors to ensure data quality, while loading the data.

Feedback Loop: Established a feedback loop where manual interventions are used to improve automated processes over time.


Data Quality Framework: Developed a data quality framework that includes standards, processes, and tools for ensuring and maintaining data quality.

**Scaling the Process:**
Parallel Processing: Use parallel processing techniques to handle data validation and cleansing for hundreds or thousands of SKUs concurrently.

Batch Processing: Implement batch processing to handle large volumes of data efficiently.

Distributed Computing: Used distributed computing frameworks like Apache Spark, AWS Glue services and many more to scale the data validation and cleansing process across multiple nodes.

**Automated Approaches:**
Data Conversion: I used Pandas' functions like, to_numeric, to_datetime function to convert  columns to the appropriate data type, handling errors as needed.

Missing Value Handling: Use dropna to remove rows with missing values.

Outlier Detection: Use statistical methods IQR to detect and handle outliers, either by removing them or replacing them with a suitable value.

Data Type Validation: Used pandas' dtypes attribute to validate that columns have the correct data types.

Data Consistency Checks: Used regular expressions or specific logic to check for consistency in column values (e.g. date formats, valid SKUs).

Data Integrity Checks: Performed checks to ensure data integrity, such as ensuring that start dates are before end dates and others.

**Importing pkgs and reading data(TSV FILE)**

In [1]:
import pandas as pd
# Maximum number of columns to display to None
pd.set_option('display.max_columns', None)

# Load the TSV file
df = pd.read_table('/content/interview_analysis_molecule_x_10mg_v1.tsv')

**Date Time and other changes made**

In [2]:
df['published_date'] = pd.to_datetime(df['published_date'])
df['start_date'] = pd.to_datetime(df['start_date'])
df['published_date_month'] = pd.to_datetime(df['published_date_month'])
df['end_date_extension'] = pd.to_datetime(df['end_date_extension'])
# Convert the 'quantity_total' column to float
df['quantity_total'] = df['quantity_total'].astype(float)
# Assume 'df' is your DataFrame containing the contract data
df['outcome'] = df['outcome'].replace({'won': 1, 'lost': 0})

In [3]:
df.dtypes

contract_id                       int64
published_date           datetime64[ns]
start_date               datetime64[ns]
duration_extension                int64
outcome                           int64
second_place_outcome             object
buyer                            object
region                           object
atc                              object
duration                          int64
contract_type                    object
sku                              object
end_date_extension       datetime64[ns]
participants_no                   int64
quantity_annual                   int64
quantity_total                  float64
maximum_price_allowed           float64
active_ingredient                object
pack_strength                    object
participants                     object
participants_price               object
published_date_month     datetime64[ns]
winner                           object
winner_price                    float64
second_place                     object
second_place_price              float64
dtype: object

**Target Variable Cleansing and manupulation**

In [4]:
# Convert 'winner_price' to numeric, coerce invalid values to NaN
df['winner_price'] = pd.to_numeric(df['winner_price'], errors='coerce')

# Remove rows with NaN values
df.dropna(subset=['winner_price'], inplace=True)

# Check for outliers
Q1 = df['winner_price'].quantile(0.25)
Q3 = df['winner_price'].quantile(0.75)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR
df = df[(df['winner_price'] >= lower_bound) & (df['winner_price'] <= upper_bound)]

# Display the DataFrame
df.head(20)

,contract_id,published_date,start_date,duration_extension,outcome,second_place_outcome,buyer,region,atc,duration,contract_type,sku,end_date_extension,participants_no,quantity_annual,quantity_total,maximum_price_allowed,active_ingredient,pack_strength,participants,participants_price,published_date_month,winner,winner_price,second_place,second_place_price
1,2,2013-04-29,2013-06-21,0,1,NaN,buyer_2,region_2,C07AB07,48,wide area,molecule_x_10mg_tablet,2017-06-30,1,54988,2.202494e+05,63442.21000,molecule_x,10mg,participants_16,0.007,2013-04-01,participants_16,0.00700,NaN,NaN
2,3,2013-06-09,2014-08-14,6,1,lost,buyer_3,region_3,C07AB07,12,regional,molecule_x_10mg_tablet,2016-02-14,2,1904,2.680639e+03,0.11635,molecule_x,10mg,participants_16|participants_23,0.014|0.07071,2013-06-01,participants_16,0.01400,participants_23,0.070710
3,4,2013-05-04,2013-05-17,19,1,NaN,buyer_4,region_4,C07AB07,36,regional,molecule_x_10mg_tablet,2017-12-31,1,1652,5.900676e+03,0.03000,molecule_x,10mg,participants_16,0.025,2013-05-01,participants_16,0.02500,NaN,NaN
5,6,2013-12-06,2014-02-21,14,1,NaN,buyer_6,region_6,C07AB07,48,regional,molecule_x_10mg_tablet,2019-04-20,1,2088,9.026168e+03,0.02550,molecule_x,10mg,participants_16,0.019,2013-12-01,participants_16,0.01900,NaN,NaN
7,8,2014-03-08,2014-05-22,10,1,lost,buyer_8,region_8,C07AB07,36,regional,molecule_x_10mg_tablet,2018-03-22,4,10332,3.195179e+04,0.08000,molecule_x,10mg,participants_16|participants_5|participants_6|...,0.03|0.08|0.034|0.04066,2014-03-01,participants_16,0.03000,participants_6,0.034000
12,13,2016-04-13,2016-06-25,6,1,lost,buyer_11,region_11,C07AB07,36,regional,molecule_x_10mg_tablet,2019-12-24,4,2800,8.589313e+03,0.07971,molecule_x,10mg,participants_6|participants_16|participants_23...,0.01699|0.07|0.06802|0.075,2016-04-01,participants_6,0.01699,participants_23,0.068020
13,14,2017-10-20,2017-09-20,3,1,NaN,buyer_12,region_12,C07AB07,48,multi-region,molecule_x_10mg_tablet,2021-12-19,1,75544,3.025601e+05,6647.87200,molecule_x,10mg,participants_16,0.02,2017-10-01,participants_16,0.02000,NaN,NaN
15,16,2017-12-29,2018-03-30,26,1,lost,buyer_14,region_4,C07AB07,48,regional,molecule_x_10mg_tablet,2024-05-30,2,14476,5.803268e+04,0.02500,molecule_x,10mg,participants_16|participants_4,0.017|0.0242,2017-12-01,participants_16,0.01700,participants_4,0.024200
16,17,2018-05-31,2018-04-01,2,1,lost,buyer_5,region_5,C07AB07,24,multi-region,molecule_x_10mg_tablet,2020-05-31,2,32875,6.652793e+04,0.02000,molecule_x,10mg,participants_16|participants_7,0.02|0.9993156095718888,2018-05-01,participants_16,0.02000,participants_7,0.999316
17,18,2019-05-26,2019-07-02,6,1,lost,buyer_3,region_3,C07AB07,36,regional,molecule_x_10mg_tablet,2023-01-01,2,20993,6.390429e+04,0.02200,molecule_x,10mg,participants_16|participants_19,0.02|0.8665684755636098,2019-05-01,participants_16,0.02000,participants_19,0.866568
18,19,2020-01-01,2020-08-04,0,1,lost,buyer_11,region_11,C07AB07,36,regional,molecule_x_10mg_tablet,2023-08-03,3,2680,8.426468e+03,0.07971,molecule_x,10mg,participants_19|participants_16|participants_23,0.01786|0.07|0.06511,2020-01-01,participants_19,0.01786,participants_23,0.065110
19,20,2019-12-19,2020-08-04,0,1,lost,buyer_11,region_11,C07AB07,36,regional,molecule_x_10mg_tablet,2023-08-03,3,2680,8.833156e+03,0.07971,molecule_x,10mg,participants_19|participants_16|participants_23,0.01786|0.07|0.06511,2019-12-01,participants_19,0.01786,participants_23,0.065110
20,21,2020-03-21,2020-06-20,12,1,NaN,buyer_15,region_9,C07AB07,36,multi-region,molecule_x_10mg_tablet,2024-06-19,1,21864,6.593100e+04,0.02200,molecule_x,10mg,participants_19,0.01607,2020-03-01,participants_19,0.01607,NaN,NaN
21,22,2020-06-10,2020-04-29,6,1,NaN,buyer_16,region_5,C07AB07,24,multi-region,molecule_x_10mg_tablet,2022-09-30,1,25750,5.175292e+04,0.02000,molecule_x,10mg,participants_19,0.0125,2020-06-01,participants_19,0.01250,NaN,NaN
23,24,2020-10-11,2020-11-25,0,1,lost,buyer_2,region_2,C07AB07,49,regional,molecule_x_10mg_tablet,2024-12-25,2,288795,1.179787e+06,963542.28000,molecule_x,10mg,participants_19|participants_23,0.0205|0.03929,2020-10-01,participants_19,0.02050,participants_23,0.039290
24,25,2021-06-09,2021-05-20,0,1,NaN,buyer_17,region_14,C07AB07,48,regional,molecule_x_10mg_tablet,2025-05-19,1,23688,9.500735e+04,0.01250,molecule_x,10mg,participants_19,0.0123,2021-06-01,participants_19,0.01230,NaN,NaN
25,26,2021-07-09,2021-07-05,6,1,NaN,buyer_12,region_12,C07AB07,48,regional,molecule_x_10mg_tablet,2026-01-05,1,40014,1.609689e+05,0.02001,molecule_x,10mg,participants_19,0.018,2021-07-01,participants_19,0.01800,NaN,NaN
26,27,2022-03-19,2022-03-31,6,1,NaN,buyer_18,region_15,C07AB07,24,multi-region,molecule_x_10mg_tablet,2024-09-30,1,28180,5.647937e+04,0.01250,molecule_x,10mg,participants_19,0.0122,2022-03-01,participants_19,0.01220,NaN,NaN
27,28,2022-07-02,2022-08-04,12,1,lost,buyer_19,region_6,C07AB07,12,regional,molecule_x_10mg_tablet,2024-08-03,2,5488,6.263290e+03,0.01600,molecule_x,10mg,participants_19|participants_23,0.015|0.01571,2022-07-01,participants_19,0.01500,participants_23,0.015710
28,29,2022-07-01,2022-06-17,24,0,won,buyer_16,region_16,C07AB07,24,regional,molecule_x_10mg_tablet,2026-06-16,2,15113,3.054884e+04,0.03929,molecule_x,10mg,participants_19|participants_23,0.034|0.02393,2022-07-01,participants_23,0.02393,participants_19,0.034000

In [5]:
df.head(3)

,contract_id,published_date,start_date,duration_extension,outcome,second_place_outcome,buyer,region,atc,duration,contract_type,sku,end_date_extension,participants_no,quantity_annual,quantity_total,maximum_price_allowed,active_ingredient,pack_strength,participants,participants_price,published_date_month,winner,winner_price,second_place,second_place_price
1,2,2013-04-29,2013-06-21,0,1,NaN,buyer_2,region_2,C07AB07,48,wide area,molecule_x_10mg_tablet,2017-06-30,1,54988,220249.442660,63442.21000,molecule_x,10mg,participants_16,0.007,2013-04-01,participants_16,0.007,NaN,NaN
2,3,2013-06-09,2014-08-14,6,1,lost,buyer_3,region_3,C07AB07,12,regional,molecule_x_10mg_tablet,2016-02-14,2,1904,2680.639219,0.11635,molecule_x,10mg,participants_16|participants_23,0.014|0.07071,2013-06-01,participants_16,0.014,participants_23,0.07071
3,4,2013-05-04,2013-05-17,19,1,NaN,buyer_4,region_4,C07AB07,36,regional,molecule_x_10mg_tablet,2017-12-31,1,1652,5900.676494,0.03000,molecule_x,10mg,participants_16,0.025,2013-05-01,participants_16,0.025,NaN,NaN

** Guideline to ML for winner price predcition**

In [ ]:
## DO not run it, it just a ML example
# Features selected
selected_columns = ['feature1', 'feature2', 'feature3']

# Select the relevant columns
selected_df = df[selected_columns]

# Calculate the correlation matrix
correlation_matrix = selected_df.corr()

# Get the correlation values for the 'winner_price' column
winner_price_correlation = correlation_matrix['winner_price']

# Print the correlation values
print(winner_price_correlation)

In [8]:
import numpy as np

# Calculate Z-score for 'winner_price'
df['winner_price_zscore'] = (df['winner_price'] - df['winner_price'].mean()) / df['winner_price'].std()

# Identify rows where the Z-score is greater than a threshold (e.g., 3)
anomalies = df[df['winner_price_zscore'].abs() > 3]

# Display rows with anomalies
print(anomalies)

Empty DataFrame
Columns: [contract_id, published_date, start_date, duration_extension, outcome, second_place_outcome, buyer, region, atc, duration, contract_type, sku, end_date_extension, participants_no, quantity_annual, quantity_total, maximum_price_allowed, active_ingredient, pack_strength, participants, participants_price, published_date_month, winner, winner_price, second_place, second_place_price, winner_price_zscore]
Index: []

In [ ]:
## DO not run it, it just a ML example
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

# Assume 'X' contains the features and 'y' contains the target variable 'winner_price'
X = df[['feature1', 'feature2', 'feature3']]
y = df['winner_price']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create a linear regression model
model = LinearRegression()

# Train the model
model.fit(X_train, y_train)

# Make predictions
y_pred = model.predict(X_test)

# Evaluate the model
mse = mean_squared_error(y_test, y_pred)
print("Mean Squared Error:", mse)

**Validation of data**

In [6]:
missing_values = df.isnull().sum()
print(missing_values)

contract_id              0
published_date           0
start_date               0
duration_extension       0
outcome                  0
second_place_outcome     9
buyer                    0
region                   0
atc                      1
duration                 0
contract_type            0
sku                      0
end_date_extension       0
participants_no          0
quantity_annual          0
quantity_total           0
maximum_price_allowed    0
active_ingredient        0
pack_strength            0
participants             0
participants_price       0
published_date_month     0
winner                   0
winner_price             0
second_place             9
second_place_price       9
dtype: int64

In [7]:
duplicate_rows = df[df.duplicated()]
print(duplicate_rows)

Empty DataFrame
Columns: [contract_id, published_date, start_date, duration_extension, outcome, second_place_outcome, buyer, region, atc, duration, contract_type, sku, end_date_extension, participants_no, quantity_annual, quantity_total, maximum_price_allowed, active_ingredient, pack_strength, participants, participants_price, published_date_month, winner, winner_price, second_place, second_place_price]
Index: []

In [ ]:
data_types = df.dtypes
print(data_types)

In [9]:
# if 'winner_price' should be positive
invalid_winner_price = df[df['winner_price'] <= 0]
print(invalid_winner_price)

Empty DataFrame
Columns: [contract_id, published_date, start_date, duration_extension, outcome, second_place_outcome, buyer, region, atc, duration, contract_type, sku, end_date_extension, participants_no, quantity_annual, quantity_total, maximum_price_allowed, active_ingredient, pack_strength, participants, participants_price, published_date_month, winner, winner_price, second_place, second_place_price]
Index: []

In [11]:
invalid_quantities = df[df['quantity_annual'] < 0]
print(invalid_quantities)

Empty DataFrame
Columns: [contract_id, published_date, start_date, duration_extension, outcome, second_place_outcome, buyer, region, atc, duration, contract_type, sku, end_date_extension, participants_no, quantity_annual, quantity_total, maximum_price_allowed, active_ingredient, pack_strength, participants, participants_price, published_date_month, winner, winner_price, second_place, second_place_price]
Index: []

In [12]:
inconsistent_dates = df[df['end_date_extension'] < df['start_date']]
print(inconsistent_dates)

Empty DataFrame
Columns: [contract_id, published_date, start_date, duration_extension, outcome, second_place_outcome, buyer, region, atc, duration, contract_type, sku, end_date_extension, participants_no, quantity_annual, quantity_total, maximum_price_allowed, active_ingredient, pack_strength, participants, participants_price, published_date_month, winner, winner_price, second_place, second_place_price]
Index: []

In [13]:
invalid_relationship = df[(df['outcome'] == 'won') & (df['second_place_outcome'] == 'won')]
print(invalid_relationship)

Empty DataFrame
Columns: [contract_id, published_date, start_date, duration_extension, outcome, second_place_outcome, buyer, region, atc, duration, contract_type, sku, end_date_extension, participants_no, quantity_annual, quantity_total, maximum_price_allowed, active_ingredient, pack_strength, participants, participants_price, published_date_month, winner, winner_price, second_place, second_place_price]
Index: []

In [14]:
invalid_maximum_prices = df[df['maximum_price_allowed'] < df['winner_price']]
print(invalid_maximum_prices)

Empty DataFrame
Columns: [contract_id, published_date, start_date, duration_extension, outcome, second_place_outcome, buyer, region, atc, duration, contract_type, sku, end_date_extension, participants_no, quantity_annual, quantity_total, maximum_price_allowed, active_ingredient, pack_strength, participants, participants_price, published_date_month, winner, winner_price, second_place, second_place_price]
Index: []